### ISSUE TITLE
Support analysis for queries inside lambda expressions

### ISSUE THREAD

**Issue by francesconi** [Zaid-Ajaj/Npgsql.FSharp.Analyzer#12]
I'm working with VS Code and the analyzer is working fine so far except it doesn't seem to analyze the queries inside lamda expressions.

![Screenshot 2020-12-06 at 09 56 11](https://user-images.githubusercontent.com/16361556/101275975-40704680-37aa-11eb-8263-329fc0eea5e2.png)

![Screenshot 2020-12-06 at 09 56 34](https://user-images.githubusercontent.com/16361556/101275980-47975480-37aa-11eb-8a96-4a5753c4cec8.png)

**Comment by Zaid-Ajaj** [comment]
Hi there @francesconi, that's an interesting edge case, I will have a look!

**Comment by Zaid-Ajaj** [comment]
Fixes as of v3.18 of the analyzer, update the nuget package and it should now be able to detect the queries. 

If the problem is resolved, please close the issue 😄

**Comment by francesconi** [comment]
It's working great! Thank you for providing a solution that fast 🚀
