### ISSUE TITLE
Question: Big (Small) Integer handling

### ISSUE THREAD

**Issue by dbrattli** [Zaid-Ajaj/Npgsql.FSharp.Analyzer#33]
**Describe the bug**

Hi @Zaid-Ajaj. How do we want to deal with integers of different size? Currently the parser cannot parse `BigInt` i.e `int64` since the integer parser uses `pint32`. I can fix this but there are some choices:

1. let `Expr.Integer` be of `int64` so it can hold all kinds of integers.
2. or we can add new types `BigInt` (and `SmallInt`). But then an array of integers might be parsed to different integer types depending on their size e.g `select array [0,54795035045033];`. Not sure if this is really a problem.
3. Get rid of `Expr.Integer` / `Expr.Float` and instead parse everything to `Numeric/Decimal`. 

Any opinions or preferences for what we should do here?

**Comment by Zaid-Ajaj** [comment]
Hi @dbrattli 

>let Expr.Integer be of int64 so it can hold all kinds of integers.

This sounds like the easiest/best solution.

**Comment by Zaid-Ajaj** [comment]
Awesome stuff @dbrattli 😍 thanks a lot 🙏 I will make some time to merge and publish soon 🚀

**Comment by dbrattli** [comment]
@Zaid-Ajaj to reduce your workload then it's fine with me if you merge without publishing (every time). Then you can publish at your own cadence. I just want to get the current changes out of the way before starting with other changes.
